/**
 * Real-life athlete data from GOAT Academy
 * 301 unique athletes extracted from attendance records
 */

export interface RealLifeAthlete {
	firstName: string;
	lastName: string;
}

// Parse full name into first and last name
function parseName(fullName: string): RealLifeAthlete {
	const parts = fullName.trim().split(" ");
	if (parts.length === 1) {
		return { firstName: parts[0] ?? "", lastName: "" };
	}
	const firstName = parts[0] ?? "";
	const lastName = parts.slice(1).join(" ");
	return { firstName, lastName };
}

// Raw athlete names from GOAT Academy attendance records
const ATHLETE_NAMES = [
	"Agus Luchini",
	"Agus Miguez",
	"Agus Raffin Davobe",
	"Agustina Alonso",
	"Agustin Sosa",
	"Aime Martinez",
	"Alma Gonzalez",
	"Alma Grau",
	"Alma Mosquera",
	"Alma Szlufman",
	"Alvaro Gibelli",
	"Ambar Astete",
	"Ambar Coronel",
	"Amelia Martin",
	"Andrea Dallaglio",
	"Anelei Cabezas",
	"Antonia Etchepare",
	"Augusto Szafowal",
	"Avril Garcia Muriel",
	"Bautista Arce",
	"Bautista Delgado Werner",
	"Belen Gusmeroti",
	"Benedicta Rey Sumay",
	"Benicio",
	"Benja Narducci",
	"Bianca Ferreiro",
	"Bianca Guido",
	"Camila Delgado Werner",
	"Camila Halac",
	"Camila Raffin Dabove",
	"Camila Rotundo",
	"Candela Matelica",
	"Candela Velazco",
	"Carola Gonzalez Pita",
	"Carolina Alzugaray",
	"Catarina Campins",
	"Catalina Acevey",
	"Catalina Echandi",
	"Catalina Gonzalez Bortolotto",
	"Catalina Greco Zenobi",
	"Catalina Melian",
	"Catalina Perlini",
	"Catalina Pons Zarate",
	"Catalina Sanchez Meli",
	"Caterina Ranieli",
	"Chiara Moras",
	"Chiara Pezzarini",
	"Ciro Bragaña",
	"Ciro Moulia Schygiel",
	"Clara Brito",
	"Clara Hagelstrom",
	"Clara Pomerantz",
	"Clemen Salomone",
	"Consuelo Torres",
	"Constantino Bahl",
	"Constanza de Seta",
	"Damiana Martinez Casas Gallardo",
	"Daniel Paradiso Bertiche",
	"Daniel Vallejos",
	"Delia Caballero",
	"Delfina Alberto",
	"Delfina Martinez",
	"Emilia Bruno",
	"Emilia Carballo",
	"Emilia Donato",
	"Emilia Gonzalez Serra",
	"Emilia Hernando",
	"Emilia Leandro",
	"Emilia Marra",
	"Emilia Rogers",
	"Emilia Udenio",
	"Emilia Zubizarreta",
	"Emi Andisco",
	"Emma Gracia Bravo",
	"Emma Mendez",
	"Emma Perez Guzman",
	"Esmeralda Dieta Vignale",
	"Euge Luchini",
	"Eva Paradiso Bertiche",
	"Farah Contador",
	"Faustina Lopez Sampo",
	"Fede Torres",
	"Felicitas Bonuccelli Gomez",
	"Felicitas Camporro",
	"Felicitas Carbonato",
	"Felicitas Garona",
	"Felicitas Granade",
	"Felicitas Ponce",
	"Felicitas Rusconi",
	"Felipe Cenizo",
	"Felipe Frutos Elorza",
	"Fiorella Schiuto",
	"Francesca Cordoba Diaz",
	"Francesca Jazmin Parma",
	"Francesca Mancini Nadal",
	"Francesca Masci",
	"Francesca Mollo",
	"Francesca Purificato",
	"Francesca Tosti",
	"Francesca Vazquez",
	"Francisca Rodriguez Morcillo",
	"Francisca Salinesi Muti",
	"Francisco Knopoff",
	"Francine Varas",
	"Gala Barbirotto",
	"Gala Vega",
	"Guadalupe Berlanga",
	"Guadalupe Reto",
	"Guadalupe Vittola",
	"Guillermina Montoya",
	"Helena Minckas",
	"Helena Nucciarone del Carril",
	"Iara Micieli",
	"Ignacio Joaquin Corti",
	"Ignacio Albanese",
	"Ignacio Carrara",
	"Irina Badino",
	"Isabela Koutoudjian",
	"Isabella Boy",
	"Isabella Bruccini",
	"Isabella Luna",
	"Isabella Palazzo",
	"Jacinta Esandi",
	"Jazmin Carlos Blas",
	"Jazmin Maldini",
	"Jazmin Salas",
	"Jazmin Vazquez",
	"Joaquina Etchepare",
	"Joaquina Vital Fassi",
	"Josefina Dinardo",
	"Josefina Escurra",
	"Josefina Lopez",
	"Juana Alvarez",
	"Juana Cappato",
	"Juana Demeco",
	"Juana Macchi",
	"Juana Maccio",
	"Juana Rodriguez Villa",
	"Juana Sanchez Azagra",
	"Juanse Andisco",
	"Julia Iribarren",
	"Julia Maisonave",
	"Julia Yannone",
	"Juliana Ferrara",
	"Juliana Sabe",
	"Julieta Bernal",
	"Julieta Lorenzini",
	"Justina Alvarez",
	"Justina Stroeder",
	"Kate Cohen",
	"Kiara Greco",
	"Lara Espinosa",
	"Lara Sanguinetti Serain",
	"Lola Alvarez Pastorino",
	"Lola Candela",
	"Luca Libertini",
	"Lucas Moreno",
	"Lucia Arcal",
	"Lucia Blajman",
	"Lucia Clemente",
	"Lucia Laiolo",
	"Lucia Pellegrino Rossi",
	"Lucia Rivas",
	"Luciana Magister",
	"Lucio Libertini",
	"Lucho Sorby",
	"Lucrecia Gonzalez",
	"Ludmila Comandu",
	"Luisana Albarracin",
	"Luna Herrera",
	"Lupe Fourcade",
	"Luz Entre Rios",
	"Macarena Citraro",
	"Magalie Nuñez",
	"Magui Pollini",
	"Maia Dinardo",
	"Maia Grosman",
	"Maia Lowestern",
	"Maite Penas",
	"Malena Cubas",
	"Malena Gomez Funes",
	"Malvina Fernandes",
	"Manuel Contreras",
	"Margarita Caballero Basconnet",
	"Maria del Pilar Faggioli",
	"Maria Barbiso",
	"Maria Emilia Mendez Picone",
	"Maria Sanchez Azagra",
	"Maria Victoria Taborda",
	"Marina Larocca",
	"Martina Alende",
	"Martina Capo",
	"Martina Czaja",
	"Martina de Otto",
	"Martina Lizama",
	"Martina Ruiz",
	"Martina Vivansan Rivet",
	"Martina Waisbaum",
	"Martina Zarzecki",
	"Mateo Campos Suarez",
	"Mathilda Quiroga",
	"Matilda Antunez",
	"Matilda Canepa",
	"Matilda Coppola",
	"Matilda Torres",
	"Mayra Quevedo",
	"Melany Manin",
	"Mery Cordoba del Rio",
	"Mia Braier",
	"Mia Briuoli",
	"Mia Brucchini",
	"Mia Eisenberg",
	"Mia Halmes",
	"Mia Mondejar",
	"Micaela Escariz",
	"Micaela Oliva",
	"Milagros Allegra Tamaro",
	"Milagros Cabrera",
	"Milena Pinotti",
	"Mora Fernandez de Oliveira",
	"Mora Kfuri",
	"More Olano",
	"Morena Mosquera",
	"Nacho Añel",
	"Nicole Sandoval",
	"Octavio",
	"Olivia Arata",
	"Olivia Canepa",
	"Olivia Cositorto",
	"Olivia Silva",
	"Pablo Sorby",
	"Paloma Mattoso Villagran",
	"Paula Oliver",
	"Paulina Manzo",
	"Paz Fermoselie",
	"Pedro Astete",
	"Pedro Bruno",
	"Pia Fernandez",
	"Pia Franze",
	"Pierina Casati",
	"Pilar Bocchi",
	"Pilar Busto Tarelli",
	"Pilar Calvo Quijano",
	"Pilar Cameselle",
	"Pilar Djiani",
	"Pilar Gibelli",
	"Pilar Maugere",
	"Pilar Meije",
	"Regina Moron",
	"Rena Rizzo",
	"Rena Torres",
	"Renata D'Onofrio",
	"Rosario Dates",
	"Rosario Leone",
	"Simon Sanchez Meli",
	"Sofia Aiupe",
	"Sofia Cabanela",
	"Sofia Iribarren",
	"Sofia Lemos",
	"Sofia Malatino",
	"Sofia Mangiarotti",
	"Sofia Marziale",
	"Sofia Mastrogiovanni",
	"Sofia Navas",
	"Sofia Salas",
	"Sofia Sapir",
	"Sofia Udenio",
	"Sofia Villareal",
	"Sol Delgado Werner",
	"Sol Frassia",
	"Sophia Lencina",
	"Tatiana Iturri",
	"Theo Bergeonneau",
	"Tobeña Agustina",
	"Trinidad Frega",
	"Trinidad Francica",
	"Uma Penza",
	"Uma Pereyna Aquerman",
	"Valen Zuccardi",
	"Valentina Aranguren",
	"Valentina Diaz Tobares",
	"Valentina Gonzalez Serra",
	"Valentino Forte",
	"Valentino Masci",
	"Valentin Iglesia Garay",
	"Vera Latrecchiana",
	"Vicente Latrecchiana",
	"Vicente Nikolin Xatruch",
	"Victoria Almada",
	"Victoria Belen Sanabria",
	"Victoria Bobbett",
	"Victoria Caprotta",
	"Victoria Fudim",
	"Victoria Garcia Arana",
	"Victoria Ianelli",
	"Victoria Nuñez",
	"Victoria Oliveira",
	"Victoria Romañoli",
	"Victoria San Agustin",
	"Violeta Bacigalupo",
	"Zoe Sammarco Gallano",
];

// Export parsed athletes
export const REAL_LIFE_ATHLETES: RealLifeAthlete[] =
	ATHLETE_NAMES.map(parseName);

// Export count for reference
export const REAL_LIFE_ATHLETE_COUNT = ATHLETE_NAMES.length;
